server:
  port: 8090
spring:
  application:
    name: resource-server
security:
  oauth2:
    client:
      client-id: client
      client-secret: 123123
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/user
    authorization:
      check-token-access: http://localhost:8080/oauth/check_token
