server:
  port: 8080

spring:
  application:
    name: oauth2-center
#  zipkin:
#      base-url: http://10.10.8.2:9050
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/alan-oauth?characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123456
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#  client:
#      service-url:
#        defaultZone: http://127.0.0.1:9010/eureka/
###actuator start####
endpoints:
  health:
    sensitive: false
    enabled: true
## 401:Unauthorized
management:
  security:
    enabled: false
###actuator end####
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    org:
      springframework:
        web: worn