server:
  port: 8080
spring:
  application:
    name: oauth2-center
  jpa:
    show-sql: true
    open-in-view: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/alan-oauth?characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  mvc:
    static-path-pattern: /static/**
